
all:
	lualatex 31c3-lightning-censorship-and-engineering.tex
	lualatex 31c3-lightning-censorship-and-engineering.tex

clean:
	-rm *.pdf
	-rm *.log
	-rm *.aux
	-rm *.toc
	-rm *.snm
	-rm *.out
	-rm *.nav

